# Generated by Django 2.2.25 on 2021-12-20 05:45

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', django_fsm.FSMField(choices=[('Draft', 'Draft'), ('Awaiting Sign A', 'Awaiting Sign A'), ('Awaiting Sign B', 'Awaiting Sign B'), ('Awaiting Sign C', 'Awaiting Sign C'), ('Awaiting Approval', 'Awaiting Approval')], default='Draft', max_length=50, protected=True)),
            ],
        ),
    ]
